packages:
  - packages/*

catalog:
  typescript: ^5.7.2
  npm-run-all: ^4.1.5

catalogs:
  eslint19:
    eslint: ^9.33.0
    '@eslint/js': ^9.33.0
    eslint-config-prettier: ^9.1.2
    typescript-eslint: ^8.39.1
  jest29:
    '@types/jest': 29.x
    jest: 29.x
    ts-jest: 29.x
    jest-environment-jsdom: ^29
