packages:
  - packages/*

catalog:
  typescript: ^5.9.2

catalogs:
  eslint19:
    '@eslint/js': ^9.34.0
    eslint: ^9.34.0
    eslint-config-prettier: ^9.1.2
    typescript-eslint: ^8.42.0
  jest:
    '@swc/jest': ^0.2.39
    '@types/jest': ^30.0.0
    jest: ^30.4.2
    jest-config: ^30.4.2
    jest-environment-jsdom: ^30.4.1
    ts-jest-resolver: ^2.0.1
  swc:
    '@swc/core': ^1.15.8

ignoredBuiltDependencies:
  - '@swc/core'
