packages:
  - 'packages/*'

catalog:
  "typescript": "^5.7.2"
  "npm-run-all": "^4.1.5"

catalogs:
  eslint19:
    "eslint": "^9.17.0"
    "@eslint/js": "^9.13.0"
    "@types/eslint__js": "^8.42.3"
    "eslint-config-prettier": "^9.1.0"
    "typescript-eslint": "^8.19.0"

  jest29:
    "@types/jest": "29.x"
    "jest": "29.x"
    "ts-jest": "29.x"
    "jest-environment-jsdom": "^29"