packages:
  - packages/*

catalog:
  npm-run-all: ^4.1.5
  typescript: ^5.9.2

catalogs:
  eslint19:
    '@eslint/js': ^9.34.0
    eslint: ^9.34.0
    eslint-config-prettier: ^9.1.2
    typescript-eslint: ^8.42.0
  jest29:
    '@types/jest': 29.x
    jest: 29.x
    jest-environment-jsdom: ^29
    ts-jest: 29.x
  jest30:
    '@types/jest': ^30.0.0
    jest: ^30.1.3
    jest-environment-jsdom: ^30.1.2
    ts-jest-resolver: ^2.0.1
    ts-jest: 29.4.1
